[project]
name = "data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lancedb>=0.34.0",
    "matplotlib>=3.11.0",
    "pandas>=3.0.3",
    "pillow>=12.3.0",
    "polars>=1.42.1",
    "seaborn>=0.13.2",
    "streamlit>=1.59.2",
    "tqdm>=4.68.4",
]
